baseURL = "https://mcanzi.github.io/"
languageCode = "en-us"
title = ""
description = "Massimiliano Canzi's personal website"
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "massimiliano canzi"
    description = "massimiliano canzi | data scientist & laboratory manager at universit√§t konstanz"
    logo = "/photos/014_FULL_01_XXX.jpg"
    twitterAuthor = "@mc_anzi"
    githubUsername = "mcanzi"
    accent = "#082D32" # "#1F1F1F" # "#1F1F1F" # dark colors do best. original: 386890
    backgroundColor = "#E9E9E9" #  "#FFFDF8" # original is f5f5f5, 255 177 171
    font = "Lora" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit

[[menu.main]]
    url = "/"
    name = "home"
    weight = 1

[[menu.main]]
    url = "/skills/education"
    name = "curriculum vitae"
    weight = 2

[[menu.main]]
    url = "/project/research"
    name = "research"
    weight = 3
    
[[menu.main]]
    url = "/photos/japan"
   name = "photography"
   weight = 4
    
#[[menu.main]]
#    url = "/tags/"
#    name = "tags"
#    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:massimiliano.canzi@uni-konstanz.de"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/mcanzi"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/mc_anzi/"
    name = "twitter"
    weight = 3

