baseURL = "https://mcanzi.github.io/"
languageCode = "en-us"
title = "Massimiliano Canzi"
description = "Massimiliano Canzi's personal website"
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "massimiliano canzi"
    description = "Laboratory Manager at Universit√§t Konstanz & PhD student at The University of Manchester"
    logo = "favicon/mcanzi.png"
    twitterAuthor = "@mc_anzi"
    githubUsername = "mcanzi"
    accent = "#1F1F1F" # dark colors do best. original: 386890
    backgroundColor = "#FFFDF8" # original is f5f5f5
    font = "Lora" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "home"
    weight = 1

[[menu.main]]
    url = "/skills/"
    name = "curriculum vitae"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "research"
    weight = 3
    
[[menu.main]]
    url = "/teaching/"
    name = "teaching"
    weight = 4

#[[menu.main]]
#    url = "/tags/"
#    name = "tags"
#    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:massimiliano.canzi@uni-konstanz.de"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/mcanzi"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/mc_anzi/"
    name = "twitter"
    weight = 3

